### ISSUE TITLE
Convenience Constructor

### ISSUE THREAD

**Issue by tknopp** [JuliaImages/ImageAxes.jl#12]
for people wanting to set the `pixelspacing` and something I previously called `offset` (in my custom code) but what more precisely is the image `center`

Came up in:
https://github.com/timholy/Images.jl/issues/542#issuecomment-270742133

But one remark/question: I usually use cell centered voxels. Since this would be done in the above constructor the question is if this is fine to you or if we need customization (I think the other two possibilities are called `nodal` and `periodic`)

**Comment by timholy** [comment]
Fixed by https://github.com/JuliaArrays/AxisArrays.jl/pull/53
