### ISSUE TITLE
Functions using axes() fail because Compat exports axes

### ISSUE THREAD

**Issue by romainFr** [JuliaImages/ImageAxes.jl#25]
Since ```axes()``` replaces ```indices()``` on master, ```Compat``` is now exporting ```axes()```, which broke a few functions in ImageAxis, for example : 

```julia
using Images
img = AxisArray(reshape(1:192, (8,8,3)), :x, :y, :time)
imedim(img)
WARNING: both AxisArrays and Compat export "axes"; uses of it in module ImageAxes must be qualified
ERROR: UndefVarError: axes not defined
Stacktrace:
 [1] timedim(::AxisArrays.AxisArray{Int64,3,Base.ReshapedArray{Int64,3,UnitRange{Int64},Tuple{}},Tuple{AxisArrays.Axis{:x,Base.OneTo{Int64}},AxisArrays.Axis{:y,Base.OneTo{Int64}},AxisArrays.Axis{:time,Base.OneTo{Int64}}}}) at /localhome/romain/.julia/v0.6/ImageAxes/src/ImageAxes.jl:136

```

This is on julia 0.6.2.

**Comment by Evizero** [comment]
I noticed this on travis as well. I think this error probably needs to be addressed in multiple packages , but the fix itself should be simple (I think); at least for `ImageAxes`.  Every occurrence of `axes` just needs to say `AxisArrays.axes` instead

**Comment by Cody-G** [comment]
I made the fix for this package and also for ImageView.  I find it a bit ugly, but I guess this will go away when we drop 0.6 support?  Then I think AxisArrays can import `axes` from base?

**Comment by rdeits** [comment]
If the meaning of `axes` in AxisArrays is consistent with the new meaning of `axes` in Base, then AxisArrays could just do `import Compat: axes`, which should work on 0.6 and 0.7

**Comment by rdeits** [comment]
Ah, but it looks like they do different things for standard Arrays, so importing isn't really an option:

```
julia> AxisArrays.axes(zeros(5, 6))
(AxisArrays.Axis{:row,Base.OneTo{Int64}}(Base.OneTo(5)), AxisArrays.Axis{:col,Base.OneTo{Int64}}(Base.OneTo(6)))

julia> Compat.axes(zeros(5, 6))
(Base.OneTo(5), Base.OneTo(6))
```

**Comment by Cody-G** [comment]
Agreed, looks like we'll have to avoid importing unless AxisArrays gets reworked.

**Comment by timholy** [comment]
I'd recommend renaming the function in AxisArrays.

I'd tackle this myself, but I'm more than swamped with the last changes to broadcasting infrastructure in 0.7/1.0, so I'm going to hope others tackle this.

**Comment by Evizero** [comment]
> I'd recommend renaming the function in AxisArrays.

This sounds like a good longterm solution. In the meantime, are there any objections to merging and tagging the hotfixes in https://github.com/JuliaImages/ImageAxes.jl/pull/26 and https://github.com/JuliaImages/ImageView.jl/pull/137 ?

**Comment by Evizero** [comment]
Its worth noting that there seems to be a plan to solve our dilemma upstream https://github.com/JuliaLang/Compat.jl/pull/442

**Comment by Cody-G** [comment]
>Its worth noting that there seems to be a plan to solve our dilemma upstream

That's nice!  Am I correct that this only rescues 0.6, and for 0.7 we'll still want to use qualified names or rename `AxisArrays.axes`?

**Comment by Evizero** [comment]
I do not know as I have not spend any time looking into 0.7 as of yet. I do believe though that a lot of updates have to be made all around the JuliaImages ecosystem. So I'd guess this depends on when the planned renaming takes place

**Comment by Evizero** [comment]
Can confirm the original issue is resolved by Compat itself. This should take care of the 0.6 side of the issue at least.
