### ISSUE TITLE
`data` might be too general a name?

### ISSUE THREAD

**Issue by cormullion** [JuliaImages/ImageAxes.jl#30]
I noticed that `data` is reserved after adding Images... Seems a bit too general a name for a very specific function?

```
julia-1.0> using Images

julia-1.0> data
data (generic function with 2 methods)
```

**Comment by timholy** [comment]
Agreed. We could either change it to `arraydata` or just force people to module-scope it. Thoughts?

**Comment by cormullion** [comment]
`arraydata` or `axesdata` look fine. (I don't use it.)
